---
- hosts: localhost
    
  tasks: 
    - name: 'Sleeping ... hold workflow to {{ time }} seconds'
      ansible.builtin.include_role:
        name: awx-functions
        tasks_from: sleep
      vars:
        time: "{{ time }}"
